
base: &base
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= ENV['TDDIUM_DB_USER'] || 'waterfall' %>
  password: <%= ENV['TDDIUM_DB_PASSWORD'] || 'blueh20' %>

development:
  <<: *base
  database: dummy_development

test:
  <<: *base
  database: <%= ENV['TDDIUM_DB_NAME'] || 'dummy_test' %>

production:
  <<: *base
  database: dummy_production
